<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BsAjnJb' shared service.

return $this->privates['.service_locator.BsAjnJb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'type' => ['privates', '.errored..service_locator.BsAjnJb.App\\Entity\\Type', NULL, 'Cannot autowire service ".service_locator.BsAjnJb": it references class "App\\Entity\\Type" but no such service exists.'],
], [
    'type' => 'App\\Entity\\Type',
]);
