<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jicXNse' shared service.

return $this->privates['.service_locator.jicXNse'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'sku' => ['privates', '.errored..service_locator.jicXNse.App\\Entity\\Sku', NULL, 'Cannot autowire service ".service_locator.jicXNse": it references class "App\\Entity\\Sku" but no such service exists.'],
], [
    'sku' => 'App\\Entity\\Sku',
]);
