<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TSEM.VO' shared service.

return $this->privates['.service_locator.TSEM.VO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profil' => ['privates', '.errored..service_locator.TSEM.VO.App\\Entity\\Profil', NULL, 'Cannot autowire service ".service_locator.TSEM.VO": it references class "App\\Entity\\Profil" but no such service exists.'],
], [
    'profil' => 'App\\Entity\\Profil',
]);
