<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yIc5BGI' shared service.

return $this->privates['.service_locator.yIc5BGI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'choice' => ['privates', '.errored..service_locator.yIc5BGI.App\\Entity\\Choice', NULL, 'Cannot autowire service ".service_locator.yIc5BGI": it references class "App\\Entity\\Choice" but no such service exists.'],
], [
    'choice' => 'App\\Entity\\Choice',
]);
