<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jwt_auth.jwt_authenticator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authentication/SimpleAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-http/Authentication/SimplePreAuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/auth0/jwt-auth-bundle/src/Security/JWTAuthenticator.php';

return $this->privates['jwt_auth.jwt_authenticator'] = new \Auth0\JWTAuthBundle\Security\JWTAuthenticator(($this->privates['jwt_auth.auth0_service'] ?? $this->load('getJwtAuth_Auth0ServiceService.php')));
