<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'web_service_user_provider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/auth0/jwt-auth-bundle/src/Security/Core/JWTUserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Security/User/WebServiceUserProvider.php';

return $this->privates['web_service_user_provider'] = new \App\Security\User\WebServiceUserProvider(($this->privates['jwt_auth.auth0_service'] ?? $this->load('getJwtAuth_Auth0ServiceService.php')));
