<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBWyxp53\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBWyxp53/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBWyxp53.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBWyxp53\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBWyxp53\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BWyxp53',
    'container.build_id' => '3b1e2e5a',
    'container.build_time' => 1564158214,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBWyxp53');
